import { useNavigate } from "react-router-dom";
import GenericButton from "../../../../components/GenericButton";
import GenericMuiTable from "../../../../components/GenericMuiTable";
import { PATH } from "../../../../../config";

export default function SuggestedItems() {
	const navigate = useNavigate();

	const columns = [
		{
			header: "Code",
			accessorKey: "mirCode",
		},
		{
			header: "Requested Date",
			accessorKey: "requestedDate",
		},
		{
			header: "Suggested Date",
			accessorKey: "suggestedDate",
		},

		{
			header: "Generated by",
			accessorKey: "user",
		},

		{
			header: "Location",
			accessorKey: "location",
		},

		{
			header: "Department",
			accessorKey: "department",
		},

		{
			header: "Action",
			accessorKey: "actions",
			enableColumnFilter: false,
			size: 30,
			muiTableHeadCellProps: {
				align: "center",
			},
			muiTableBodyCellProps: {
				align: "center",
			},
			Cell: () => (
				<div className="flex justify-center">
					<GenericButton
						type="primary"
						lable="Review"
						onClick={() => navigate(PATH.MIR_ISSUE_SUGGESTED_REVIEW)}
					/>
				</div>
			),
		},
	];
	const data = [
		{
			mirCode: "2132",
			requestedDate: "11/24/2023",
			suggestedDate: "11/24/2023",
			user: "John Doe",
			location: "New York",
			department: "IT",
		},
		{
			mirCode: "2132",
			requestedDate: "11/24/2023",
			suggestedDate: "11/24/2023",
			user: "John Doe",
			location: "New York",
			department: "IT",
		},
		{
			mirCode: "2132",
			requestedDate: "11/24/2023",
			suggestedDate: "11/24/2023",
			user: "John Doe",
			location: "New York",
			department: "IT",
		},
		{
			mirCode: "2132",
			requestedDate: "11/24/2023",
			suggestedDate: "11/24/2023",
			user: "John Doe",
			location: "New York",
			department: "IT",
		},
	];
	return (
		<>
			<GenericMuiTable columns={columns} data={data} />
		</>
	);
}
