import { Form, Space } from "antd";
import GenericCard from "../../../../components/GenericCard";
import TitleSearchButton from "../../../../components/TitleSearchButton";
import FormFieldGroup from "../../../../components/form/FormFieldGroup";
import { useState } from "react";
import GenericButton from "../../../../components/GenericButton";
import { PATH } from "../../../../../config";
import { useNavigate } from "react-router-dom";
import SuggestedItemsCardStore from "../../Shared/components/SuggestedItemsCardStore";

const Review = () => {
	const [form] = Form.useForm();
	const navigate = useNavigate();
	const [inputFields, setInputFields] = useState({});
	const onFinish = (values) => {
		console.log("Received values:", values);
		console.log(inputFields);
	};

	const handleInputChange = (fieldName, value) => {
		setInputFields((prevInputFields) => ({
			...prevInputFields,
			[fieldName]: value,
		}));
	};
	const generateFields = (fieldsConfig, handleInputChange) => {
		return (
			<FormFieldGroup
				fieldsConfig={fieldsConfig}
				handleInputChange={handleInputChange}
			/>
		);
	};

	return (
		<>
			<TitleSearchButton title="IRF Review" importDropdown printBtn />
			<GenericCard>
				<Form
					form={form}
					name="myForm"
					initialValues={{ remember: true }}
					onFinish={onFinish}
				>
					{generateFields(fieldsConfig, handleInputChange)}
				</Form>
			</GenericCard>
			<div className="mt-5">
				<TitleSearchButton title="Suggested Items" />
				<SuggestedItemsCardStore />
				<SuggestedItemsCardStore />
			</div>
			<div className="flex justify-between gap-3">
				<GenericButton
					type="outline"
					lable="Back"
					onClick={() => navigate(-1)}
				/>

				<Space>
					<GenericButton
						type="primary"
						lable="OK"
						onClick={() => navigate(PATH.MIR_ISSUE_LIST)}
					/>
				</Space>
			</div>
		</>
	);
};

export default Review;

export const fieldsConfig = [
	{
		type: "dropdown",
		label: "From Store",
		name: "fromStore",
		rules: [{ required: true, message: "Please select this field!" }],
		options: [
			{ value: "usa", label: "USA" },
			{ value: "canada", label: "Canada" },
			{ value: "uk", label: "UK" },
		],
	},
	{
		type: "input",
		label: "To Store",
		name: "toStore",
		rules: [{ required: true, message: "Please input this field!" }],
	},

	{
		type: "input",
		label: "Generated by",
		name: "Fahad",
		rules: [{ required: true, message: "Please input this field!" }],
	},
	{
		type: "input",
		label: "Date",
		name: "date",
		rules: [{ required: true, message: "Please input this field!" }],
	},
	{
		type: "input",
		label: "Remarks",
		name: "remarks",
		rules: [{ required: true, message: "Please input this field!" }],
	},
	{
		type: "dropdown",
		label: "Demand type",
		name: "demandtype",
		rules: [{ required: true, message: "Please input this field!" }],
	},
];
