/* eslint-disable react/prop-types */
import { Spin } from "antd";
import BasicDetails from "./components/BasicDetail";
import { useNavigate, useParams } from "react-router-dom";
import TitleSearchButton from "../../../components/TitleSearchButton";
import GenericCard from "../../../components/GenericCard";
import CardButtonFilterGroup from "../../../components/CardButtonFilterGroup";
import GenericMuiTable from "../../../components/GenericMuiTable";
import GenericButton from "../../../components/GenericButton";
import { useGetConsumptionByIdQuery } from "../../../redux/slices/consumption";

export default function View() {
  const navigate = useNavigate();
  const { id } = useParams();

  const {
    data: consumptiontData,
    isLoading,
    isFetching,
  } = useGetConsumptionByIdQuery({ id });

  const getFormattedData = () => {
    if (consumptiontData) {
      return consumptiontData?.itemsConsumption?.map((item) => {
        return {
          itemCode: item?.item?.itemCode,
          name: item?.item?.name,
          itemDesc: item?.item?.description,
          createDateTime: item?.item?.createDateTime,
          sinTotal: item?.sinTotal,
          consumeQty: item?.consumeQty,
          patients: item?.patients,
        };
      });
    }

    return null;
  };

  const CONSUMPTION_VIEW_COLUMN = [
    {
      header: "Item code",
      accessorKey: "itemCode",
      size: 120,
    },
    {
      header: "Name",
      accessorKey: "name",
      size: 120,
    },
    {
      header: "Item Description",
      accessorKey: "itemDesc",
      size: 250,
    },
    {
      header: "Total Issued",
      accessorKey: "sinTotal",
      size: 120,
    },
    {
      header: "Consumed Quanity",
      accessorKey: "consumeQty",
      size: 120,
    },
    {
      header: "Patients",
      accessorKey: "patients",
      size: 120,
    },
  ];

  return isLoading || isFetching ? (
    <div className="text-center">
      <Spin />
    </div>
  ) : (
    <>
      <GenericCard>
        <TitleSearchButton
          title="View  Consumption"
          id={consumptiontData?.consumptionCode}
          subTitle={`Generated by ${consumptiontData?.department?.name}`}
        />
      </GenericCard>
      <CardButtonFilterGroup
        topSpace
        title={{ text: "Requested Items", level: 2 }}
      >
        <GenericMuiTable
          columns={CONSUMPTION_VIEW_COLUMN}
          data={getFormattedData() || []}
          className="cl-table"
          rowSelection={false}
          enableColumnFilters={false}
          simpleTable
          isLoading={isLoading || isFetching}
        />
      </CardButtonFilterGroup>
      <div className="mt-5">
        <BasicDetails data={consumptiontData} />
      </div>
      <div className="mt-5">
        <GenericButton
          type="outline"
          lable="Back"
          onClick={() => navigate(-1)}
        />
      </div>
    </>
  );
}
