/* eslint-disable no-mixed-spaces-and-tabs */
/* eslint-disable react/prop-types */
import { useNavigate } from "react-router-dom";
import { useEffect, useState } from "react";
import { useSelector } from "react-redux";

import GenericMuiTable from "../../../components/GenericMuiTable";
import { PATH } from "../../../../config";
import { PlusOutlined } from "@ant-design/icons";
import ActionDropdown from "../../../components/ActionDropdown";
import AppConfirmDialog from "../../../components/AppConfirmDialog";
import CustomTabs from "../../../components/CustomTabs";
import ActionPending from "./ActionPending/Index";
import StatusTags from "../../../components/StatusTags";
import {
	useDeleteIrrMutation,
	useLazyGetIrrListQuery,
} from "../../../redux/slices/IRR";
import { getFormattedDate } from "../../../utils/helper";
import useNotification from "../../../components/Notification";
import CardButtonFilterGroup from "../../../components/CardButtonFilterGroup";
import useDebounce from "../../../hooks/useDebounce";
import LOOKUPS from "../../../utils/lookups";
import {
	ACTION_KEYS,
	MAKEYS,
	MIR_STAGE,
	MIR_STATUS,
} from "../../../utils/constant";
import OrderTrackModal from "../../MIR/Shared/components/OrderTrackModal";

export default function My() {
	const [tableOptions, setTableOptions] = useState({
		filters: {},
		pagination: {
			pageSize: 10,
			pageIndex: 0,
		},
	});
	const [showDeleteDialog, setShowDeleteDialog] = useState(false);
	const { openNotification, contextHolder } = useNotification();
	const [showTrack, setShowTrack] = useState({ show: false, id: null });

	const { user, permissions } = useSelector((state) => state.auth);
	const departmentId = user?.activeRole?.departmentId;

	const [
		irrListData,
		{ data: IrrList, isLoading: irrListLoading, isFetching },
	] = useLazyGetIrrListQuery();
	const [deleteIrr, { isLoading: deleteLoading }] = useDeleteIrrMutation();

	const handleDelete = async (id) => {
		const { error } = await deleteIrr(id);
		if (!error) {
			openNotification("success", "Request deleted successfully");
		} else {
			openNotification("error", "Error deleting request");
		}
	};

	const debouncedTableOptions = useDebounce(tableOptions, 1000, ["mrrCode"]);

	useEffect(() => {
		if (debouncedTableOptions) {
			irrListData({ tableOptions: debouncedTableOptions, departmentId });
		}
	}, [debouncedTableOptions, irrListData, departmentId]);

	const hasPermission = (action) => {
		return permissions?.[MAKEYS.IRR_GENERATE]?.[action];
	};

	const columns = [
		{
			header: "Code",
			accessorKey: "mrrCode",
		},
		{
			header: "Generated Date",
			accessorKey: "createDateTime",
			filterVariant: "date",
		},
		// {
		//   header: "Generated By",
		//   accessorKey: "fromDepartment.name",
		// },
		{
			header: "Status",
			accessorKey: "status",
			size: 250,
			Cell: ({ cell }) => <StatusTags status={cell?.getValue()} />,
			filterSelectOptions: LOOKUPS.MIR_STATUS,
			filterVariant: "select",
		},
		{
			header: "stage",
			accessorKey: "stage",
			size: 250,
			Cell: ({ cell }) => <span>{cell?.getValue()?.replace(/_/g, " ")}</span>,
			filterSelectOptions: [
				{ label: "Completed", value: "COMPLETED" },
				{ label: "HOD Approval", value: "HOD_APPROVAL" },
				{ label: "Store Approval", value: "STORE_APPROVAL" },
				{ label: "Partial Complete", value: "PARTIAL_COMPLETE" },
			],
			filterVariant: "select",
		},
		{
			header: "Actions",
			accessorKey: "id",
			enableColumnFilter: false,
			align: "center",
			size: 30,
			muiTableHeadCellProps: {
				align: "center",
			},
			muiTableBodyCellProps: {
				align: "center",
			},
			// eslint-disable-next-line no-unused-vars
			Cell: ({ cell, row }) => (
				<ActionDropdown
					editOnClick={
						hasPermission(ACTION_KEYS.EDIT)
							? [MIR_STATUS.PENDING].includes(cell.row.original.status) &&
							  [MIR_STAGE.HOD_APPROVAL].includes(cell.row.original.stage)
								? () =>
										navigate(PATH.MRR_UPDATE.replace(":id", cell?.getValue()))
								: undefined
							: undefined
					}
					viewOnClick={
						hasPermission(ACTION_KEYS.VIEW)
							? () =>
									navigate(
										PATH.MRR_GENERATE_VIEW.replace(":id", cell?.getValue())
									)
							: undefined
					}
					deleteOnClick={
						hasPermission(ACTION_KEYS.DELETE)
							? [MIR_STATUS.PENDING].includes(cell.row.original.status) &&
							  [MIR_STAGE.HOD_APPROVAL].includes(cell.row.original.stage)
								? () => handleDelete(cell?.getValue())
								: undefined
							: undefined
					}
					trackOnClick={
						hasPermission(ACTION_KEYS.TRACK)
							? () => {
									setShowTrack({ show: true, id: cell?.getValue() });
							  }
							: undefined
					}
				/>
			),
		},
	];

	const data = IrrList?.list?.map((item) => {
		return {
			...item,
			createDateTime: getFormattedDate(item?.createDateTime, "DD-MM-YYYY"),
		};
	});

	const navigate = useNavigate();
	const MyMRR = (
		<>
			{contextHolder}

			<CardButtonFilterGroup
				title={{ text: "My Inventory Return Request", level: 1 }}
				button={
					hasPermission(ACTION_KEYS.ADD)
						? {
								label: "Generate New IRR",
								icon: <PlusOutlined />,
								onClick: () => navigate(PATH.MRR_GENERATE),
						  }
						: undefined
				}
			>
				<GenericMuiTable
					columns={columns}
					data={data || []}
					isLoading={irrListLoading || deleteLoading || isFetching}
					manualPagination={true}
					totalRecords={IrrList?.totalRows}
					updatePaginationFunc={(data) =>
						setTableOptions({ ...tableOptions, pagination: data })
					}
					updateColumnFilters={setTableOptions}
					enableGlobalFilter={false}
					manualFiltering={true}
				/>
			</CardButtonFilterGroup>
			<AppConfirmDialog
				showModal={showDeleteDialog}
				description={`Are you sure you want to delete ?`}
				handleCancel={() => setShowDeleteDialog(false)}
				handleOk={() => setShowDeleteDialog(false)}
			/>
		</>
	);
	const tabsData = [
		{
			label: "My Inventory Return Request",
			content: MyMRR,
		},
		{
			label: "Action Pending",
			content: <ActionPending />,
		},
	];
	return (
		<>
			<CustomTabs tabsData={tabsData} />
			<OrderTrackModal
				show={showTrack?.show}
				onClose={() => setShowTrack({ show: false, id: null })}
				isTrackId={showTrack?.id}
			/>
		</>
	);
}
